---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard
---


```{r setup}
#set global output chunk options
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, collapse = F, highlight = F, results = "asis")
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
#clear memory
rm(list = ls())
#penalize excessive significant figures
options(digits = 3)
#preventing scientific notation
options(scipen = 10)

#packages used in this analysis, will install packages if not installed
if(!require(knitr)){
    install.packages("knitr", dependencies = TRUE)
    library(knitr)
}
if(!require(tidyverse)){
    install.packages("tidyverse", dependencies = TRUE)
    library(tidyverse)
}
if(!require(haven)){
    install.packages("haven", dependencies = TRUE)
    library(haven)
}
if(!require(janitor)){
    install.packages("janitor", dependencies = TRUE)
    library(janitor)
}

if(!require(ggthemes)){
    install.packages("ggthemes", dependencies = TRUE)
    library(ggthemes)
}

if(!require(readxl)){
    install.packages("readxl", dependencies = TRUE)
    library(readxl)
}

library(RColorBrewer)
library(ggalt)
library(ggrepel)
library(kableExtra)
library(waffle)
library(cowplot)
library(patchwork)
library(flexdashboard)
```

```{r}
#Reading in the data 
winter <- readxl::read_xlsx("sel_indicators_survey.xlsx", sheet = 1)
fall <- readxl::read_xlsx("sel_indicators_survey.xlsx", sheet = 2)
demo <- readxl::read_xlsx("sel_indicators_survey.xlsx", sheet = 3)

theme_set(theme_classic())
```

```{r}
#Some quick data cleaning
# Winter sheet 
winter <- winter %>% 
  select(-c(1)) %>% 
  clean_names() %>% 
  rename(
    sid = 1,
    belong = 2,
    `trust adult` = 3,
    `voice matters` = 4,
    `excited to learn` = 5, 
    `peers care` = 6,
    `I care about peers` = 7,
    `teachers care` = 8,
    `stuck strategies` = 9,
    `upset strategies` = 10,
    `problem-solving strategies` = 11,
    `share strategies with family` = 12,
    `Wants school adult` = 13) %>% 
  mutate(
    quarter = "W. '21")

# Fall sheet 
fall <- fall %>% 
  select(-c(1)) %>% 
  clean_names() %>% 
  rename(
    sid = 1,
    belong = 2,
    `trust adult` = 3,
    `voice matters` = 4,
    `excited to learn` = 5, 
    `peers care` = 6,
    `I care about peers` = 7,
    `teachers care` = 8,
    `stuck strategies` = 9,
    `upset strategies` = 10,
    `problem-solving strategies` = 11,
    `share strategies with family` = 12,
    `Wants school adult` = 13) %>% 
  mutate(
    quarter = "F. '20")

# combine fall and winter data set 
wf <- rbind(winter, fall)

# only keep numbers in SID column 
wf <- wf %>% 
  mutate(sid = parse_number(wf$sid, trim_ws = T))

# Clean demo names 
demo <- demo %>% 
  clean_names() %>% 
  rename(
    `home language` = 3,
     gender = gen)

# Match WF dataset to demographic dataset 
sel_df <- left_join(wf, demo, by = "sid") 

#Change likert scale to numbers 
sel_df[sel_df == "Siempre // Always"] <- "3"
sel_df[sel_df == "Casi Siempre // Usually"] <- "2" 
sel_df[sel_df == "De Vez En Cuando // Sometimes"] <- "1" 
sel_df[sel_df == "Nunca // Never"] <- "0"
sel_df[sel_df == "Si // Yes"] <- "1"
sel_df[sel_df == "No"] <- "0"

sel_df[sel_df == "Black or African American"] <- "Black or AA"
sel_df[sel_df == "Native Hawaiian or Other Pacific Islander"] <- "NHPI" 
sel_df[sel_df == "American Indian or Alaska Native"] <- "AIAN" 

# clean names
sel_df <- clean_names(sel_df) 

#Use the hablar package to change character variables that should be integer/numeric to interger
sel_df <- sel_df %>% hablar::retype() 

sel_long <- sel_df %>% pivot_longer(cols = belong:wants_school_adult, names_to = "domain", values_to = "score")

# remove underscores from strings in domain column
sel_long$domain <- str_replace_all(sel_long$domain, "_", " ")

# Make some varibles factors in wf data set 

# Change observation Names 
wf[wf == "Siempre // Always"] <- "Siempre"
wf[wf == "Casi Siempre // Usually"] <- "Casi Siempre" 
wf[wf == "De Vez En Cuando // Sometimes"] <- "De Vez En Cuando" 
wf[wf == "Nunca // Never"] <- "Nunca"
wf[wf == "Si // Yes"] <- "Si"

# Make some columns factors in wf dataframe 
wf <- wf %>% mutate_if(is.character, as.factor)

# Change factor levels
wf$belong <- factor(wf$belong, levels = c("Nunca", "De Vez En Cuando", "Casi Siempre", "Siempre"))
wf$`trust adult` <- factor(wf$`trust adult`, levels = c("Nunca", "De Vez En Cuando", "Casi Siempre", "Siempre"))
wf$`voice matters` <- factor(wf$`voice matters`, levels = c("Nunca", "De Vez En Cuando", "Casi Siempre", "Siempre"))
wf$`excited to learn` <- factor(wf$`excited to learn`, levels = c("Nunca", "De Vez En Cuando", "Casi Siempre", "Siempre"))
wf$`peers care` <- factor(wf$`peers care`, levels = c("Nunca", "De Vez En Cuando", "Casi Siempre", "Siempre"))
wf$`teachers care` <- factor(wf$`teachers care`, levels = c("Nunca", "De Vez En Cuando", "Casi Siempre", "Siempre"))
wf$`I care about peers` <- factor(wf$`I care about peers`, levels = c("Nunca", "De Vez En Cuando", "Casi Siempre", "Siempre"))
wf$`stuck strategies` <- factor(wf$`stuck strategies`, levels = c("Nunca", "De Vez En Cuando", "Casi Siempre", "Siempre"))
wf$`upset strategies` <- factor(wf$`upset strategies`, levels = c("Nunca", "De Vez En Cuando", "Casi Siempre", "Siempre"))
wf$`problem-solving strategies` <- factor(wf$`problem-solving strategies`, levels = c("Nunca", "De Vez En Cuando", "Casi Siempre", "Siempre"))
wf$`share strategies with family` <- factor(wf$`share strategies with family`, levels = c("Nunca", "De Vez En Cuando", "Casi Siempre", "Siempre"))
wf$quarter <- factor(wf$quarter, levels = c("W. '21", "F. '20"))
```


Column {data-width=650}
-----------------------------------------------------------------------

## Demographic Data / Datos Demográficos

## Género (Gender)
```{r}
# Fall Gender 
table <- sel_df %>%
  filter(quarter == "F. '20") %>%
  filter(!is.na(gender)) %>% 
  count("Gender" = gender ) %>%
  adorn_percentages(denominator = "col") %>% 
  adorn_totals("row") %>% 
  adorn_pct_formatting() %>%
  adorn_ns()

kable(table, caption = "Fall 2020 SEL Survey Respondents' Gender", col.names = c("Gender", "Percent (Total)"))%>% kable_styling(full_width = T, bootstrap_options = c("striped", "responsive"), position = "left", fixed_thead = T) %>% row_spec(c(3), bold = T, color = "#049E64")  
```

```{r}
# Winter Gender 
table <- sel_df %>%
  filter(quarter == "W. '21") %>%
  filter(!is.na(gender)) %>% 
   count("Gender" = gender ) %>%
   adorn_percentages(denominator = "col") %>% 
   adorn_totals("row") %>% 
  adorn_pct_formatting() %>%
  adorn_ns()

kable(table, caption = "Winter 2021 SEL Survey Respondents' Gender", col.names = c("Gender", "Percent (Total)"))%>% kable_styling(full_width = T, bootstrap_options = c("striped", "responsive"), position = "left", fixed_thead = T) %>% row_spec(c(3), bold = T, color = "#049E64") 
```

## La Raza (Race)
```{r}
# Fall Race 
table <- sel_df %>%
  filter(quarter == "F. '20") %>%
  filter(!is.na(race)) %>% 
   count("Race" = race ) %>%
   arrange(desc(n)) %>% 
   adorn_totals("row") %>% 
   adorn_percentages(denominator = "col") %>% 
  adorn_pct_formatting() %>%
  adorn_ns()

kable(table, caption = "Fall 2020 SEL Survey Respondents' Race", col.names = c("Race", "Percent (Total)"))%>% kable_styling(full_width = T, bootstrap_options = c("striped", "responsive"), position = "left", fixed_thead = T) %>% row_spec(c(8), bold = T, color = "#049E64")  
```

```{r}
# Winter Race 
table <- sel_df %>%
  filter(quarter == "W. '21") %>% 
  filter(!is.na(race)) %>% 
   count("Race" = race ) %>%
   arrange(desc(n)) %>% 
   adorn_totals("row") %>% 
   adorn_percentages(denominator = "col") %>% 
  adorn_pct_formatting() %>%
  adorn_ns()

kable(table, caption = "Winter 2021 SEL Survey Respondents' Race", col.names = c("Race", "Percent (Total)"), subcaption = "blue is new") %>% kable_styling(full_width = T, bootstrap_options = c("striped", "responsive"), position = "left", fixed_thead = T) %>% row_spec(c(8), bold = T, color = "#049E64") 
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

